# Generated by Django 4.0.3 on 2022-03-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinstance',
            name='registration',
            field=models.CharField(db_index=True, max_length=6, verbose_name='Registration'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='vin',
            field=models.CharField(db_index=True, max_length=17, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(db_index=True, help_text='Car manufacturer', max_length=50, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(db_index=True, help_text='Car model', max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
    ]
