# Generated by Django 4.0.3 on 2022-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_carinstance_registration_alter_carinstance_vin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'New'), (10, 'Working'), (20, 'Finished repairs'), (30, 'Closed (paid)'), (50, 'Removed')], default=0, verbose_name='Status'),
        ),
    ]
