# Generated by Django 4.0.3 on 2022-03-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='picture',
            field=models.ImageField(default='service/default.png', upload_to='', verbose_name='Picture'),
        ),
    ]
