# Generated by Django 4.0.3 on 2022-03-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_carinstance_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinstance',
            name='picture',
            field=models.ImageField(default='service/img/default.png', upload_to='', verbose_name='Picture'),
        ),
    ]
