# Generated by Django 4.0.3 on 2022-03-17 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_carinstance_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 24), null=True, verbose_name='Due back'),
        ),
    ]
