# Generated by Django 4.0.3 on 2022-03-17 19:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_order_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='Description'),
        ),
    ]
