# Generated by Django 4.0.3 on 2022-03-21 17:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0007_carinstance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 28), null=True, verbose_name='Due back'),
        ),
        migrations.CreateModel(
            name='OrderMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', tinymce.models.HTMLField(blank=True, default='', max_length=1000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_messages', to='service.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Message',
                'verbose_name_plural': 'Order Messages',
            },
        ),
    ]
