# Generated by Django 4.0.3 on 2022-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_order_due_back_ordermessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sum'),
        ),
    ]
